function [fitresult, gof] = ghc_fit(x, mean_ghc)
%CREATEFIT(X,MEAN_GHC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: mean_ghc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Apr-2017 15:23:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, mean_ghc );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.181343782861976 0.0995621803771437 0.482610009174427];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'mean_ghc vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel x
%ylabel mean_ghc
%grid on


